services:
  celeriant-server:
    image: ghcr.io/celeriant/celeriant:latest
    ports:
      - "10000:10000"
    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command:
      - "--standalone"
      - "--data-root"
      - "/var/lib/celeriant"
      - "--client-port"
      - "10000"
      - "--num-shards"
      - "1"
      - "--log-level"
      - "warn"
    volumes:
      - celeriant-data:/var/lib/celeriant

volumes:
  celeriant-data:
