<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <RootNamespace>Celeriant.Client</RootNamespace>
    <AssemblyName>Celeriant.Client</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Celeriant.Client.Tests" />
    <InternalsVisibleTo Include="Celeriant.Client.IntegrationTests" />
    <InternalsVisibleTo Include="Celeriant.Client.Benchmark" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.187" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.4" />
    <PackageReference Include="Snappier" Version="1.1.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
